### ISSUE TITLE
Adding the end time to the dropdown

### ISSUE THREAD

**Issue by scottandrews98** [baperrou/WooBooking-Dropdown-coursedates#1]
Hi, I have managed to add this to the plugin. If you like I can share with you the code to fix it?

<img width="337" alt="screenshot 2019-02-07 at 7 57 39 pm" src="https://user-images.githubusercontent.com/22369584/52439104-a63e0980-2b12-11e9-8630-d008876e356c.png">

**Comment by baperrou** [comment]
Thank you for the feedback Scott.  I purposely chose not to show the end date as it made the drop down list very long.  I haven’t had anyone else ask for it so I didn’t add it to the plugin.

Glad you modified it to your liking.

All the best,
Beth

Beth Perrou
plugins@doitsimply.co.uk
